# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hello Ajahne
# email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  const blog = ['learning', 'leadership', 'languages', 'life'];
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ajahne.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ajahne
author:
  name             : "Ajahne Santa Anna"
  avatar           : "/assets/images/bio-pic.jpg"
  bio              : "VP Technology & Engineering @truechoicesolutions"
  location         : "Brooklyn"
  github           : "ajahne"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.12.1"

words_per_minute         : 200
google_analytics         : UA-126257783-1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


paginate: 8 # amount of posts to show
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
